'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';
import './mira.css';

type Mood = 'calm' | 'warm' | 'playful' | 'sad' | 'curious' | 'guarded';
type Memory = { text: string; createdAt: number };
type MiraState = { trust: number; closeness: number; tension: number; memories: Memory[]; firstName: string; mood: Mood };
type ChatMessage = { role: 'mira' | 'user'; text: string; event?: boolean };
type PhoneMessage = { id: string; direction: 'mira' | 'player'; body: string; kind: string; readAt?: string | null; createdAt: number };
type LifeEvent = { id: string; title: string; body: string; kind: string; mood: Mood; occurredAt: number };

const KEY = 'between-us-mira-v1', SAVE = 'between-us-save-v3', PHONE_KEY = 'between-us-mira-phone-v1', LIFE_KEY = 'between-us-mira-life-v1', PLAYER_KEY = 'between-us-player-id-v1', LAST_SEEN_KEY = 'between-us-mira-last-seen-v1', LAST_EVENT_KEY = 'between-us-mira-last-event-v1';
const moods: Mood[] = ['calm', 'warm', 'playful', 'sad', 'curious', 'guarded'];
const defaultState: MiraState = { trust: 0, closeness: 0, tension: 0, memories: [], firstName: 'ты', mood: 'calm' };
function uid() { return typeof crypto?.randomUUID === 'function' ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function loadJson<T>(key: string, fallback: T): T { try { return JSON.parse(localStorage.getItem(key) || 'null') ?? fallback; } catch { return fallback; } }
function loadState(): MiraState { try { const saved = JSON.parse(localStorage.getItem(KEY) || 'null'); const game = JSON.parse(localStorage.getItem(SAVE) || 'null'); if (saved) return { ...defaultState, ...saved, memories: Array.isArray(saved.memories) ? saved.memories : [] }; return { ...defaultState, trust: Number(game?.trust || 0), closeness: Math.max(0, Number(game?.trust || 0) * 2 - Number(game?.tension || 0)), tension: Number(game?.tension || 0), memories: Array.isArray(game?.memories) ? game.memories.map((text: string) => ({ text, createdAt: Date.now() })) : [] }; } catch { return defaultState; } }
function playerId() { let id = localStorage.getItem(PLAYER_KEY); if (!id) { id = uid(); localStorage.setItem(PLAYER_KEY, id); } return id; }
function relationship(s: MiraState) { return Math.max(0, Math.min(100, 50 + s.closeness * 4 + s.trust * 2 - s.tension * 3)); }

export default function MiraPage() {
  const [state, setState] = useState(defaultState), [chat, setChat] = useState<ChatMessage[]>([]), [phone, setPhone] = useState<PhoneMessage[]>([]), [life, setLife] = useState<LifeEvent[]>([]);
  const [panel, setPanel] = useState<'chat' | 'phone' | 'life'>('chat'), [mobileView, setMobileView] = useState<'story' | 'mira'>('mira'), [input, setInput] = useState(''), [busy, setBusy] = useState(false), [emailInput, setEmailInput] = useState(''), [emailSent, setEmailSent] = useState(false), [identity, setIdentity] = useState<'local' | 'device' | 'account'>('local'), [storyKey, setStoryKey] = useState(0);
  const persist = (next: MiraState) => { setState(next); localStorage.setItem(KEY, JSON.stringify(next)); };
  const persistPhone = (next: PhoneMessage[]) => { const x = next.slice(-100); setPhone(x); localStorage.setItem(PHONE_KEY, JSON.stringify(x)); };
  const persistLife = (next: LifeEvent[]) => { const x = next.slice(-40); setLife(x); localStorage.setItem(LIFE_KEY, JSON.stringify(x)); };
  async function saveRemote(next: MiraState) { const { data: { session } } = await supabase.auth.getSession(); if (!session?.user) return; await supabase.from('mira_player_profiles').upsert({ user_id: session.user.id, first_name: next.firstName === 'ты' ? null : next.firstName, trust: next.trust, affection: next.closeness, tension: next.tension, mood: next.mood, memories: next.memories, player_metadata: { browserPlayerId: playerId() }, last_seen_at: new Date().toISOString() }, { onConflict: 'user_id' }); }
  async function savePhone(items: PhoneMessage[]) { const { data: { session } } = await supabase.auth.getSession(); if (!session?.user) return; await Promise.all(items.slice(-10).map(m => supabase.from('mira_phone_messages').upsert({ id: m.id, user_id: session.user.id, direction: m.direction, body: m.body, kind: m.kind, read_at: m.readAt || null, created_at: new Date(m.createdAt).toISOString() }, { onConflict: 'id' }))); }
  async function hydrate() { const local = loadState(); const localPhone = loadJson<PhoneMessage[]>(PHONE_KEY, []); const localLife = loadJson<LifeEvent[]>(LIFE_KEY, []); setState(local); setPhone(localPhone); setLife(localLife); setChat([{ role: 'mira', text: local.memories.length ? 'Ты вернулся. Я помню больше, чем в прошлый раз.' : 'Привет. Я Мира. Здесь можно говорить со мной и одновременно продолжать историю.' }]); let { data: { session } } = await supabase.auth.getSession(); if (!session?.user) { const a = await supabase.auth.signInAnonymously(); session = a.data.session; if (!session?.user) return; setIdentity('device'); } else setIdentity(session.user.email ? 'account' : 'device'); const [{ data: profile }, { data: rp }, { data: rl }] = await Promise.all([supabase.from('mira_player_profiles').select('*').eq('user_id', session.user.id).maybeSingle(), supabase.from('mira_phone_messages').select('*').eq('user_id', session.user.id).order('created_at', { ascending: true }).limit(100), supabase.from('mira_life_events').select('*').eq('user_id', session.user.id).order('occurred_at', { ascending: true }).limit(40)]); if (profile) { const remote = { trust: Number(profile.trust || 0), closeness: Number(profile.affection || 0), tension: Number(profile.tension || 0), memories: Array.isArray(profile.memories) ? profile.memories.slice(-30) : [], firstName: profile.first_name || 'ты', mood: moods.includes(profile.mood) ? profile.mood : 'calm' as Mood }; persist(remote); setChat([{ role: 'mira', text: remote.memories.length ? 'Я помню наш разговор. Давай продолжим.' : 'Я здесь. Давай знакомиться.' }]); } else await saveRemote(local); if (rp?.length) persistPhone(rp.map((m: any) => ({ id: m.id, direction: m.direction, body: m.body, kind: m.kind, readAt: m.read_at, createdAt: Date.parse(m.created_at) }))); if (rl?.length) persistLife(rl.map((e: any) => ({ id: e.id, title: e.title, body: e.body, kind: e.kind, mood: moods.includes(e.mood) ? e.mood : 'calm', occurredAt: Date.parse(e.occurred_at) })));
  }
  useEffect(() => { void hydrate(); const last = Number(localStorage.getItem(LAST_SEEN_KEY) || 0), prevEvent = Number(localStorage.getItem(LAST_EVENT_KEY) || 0), away = last ? (Date.now() - last) / 36e5 : 0; localStorage.setItem(LAST_SEEN_KEY, String(Date.now())); if (away >= .5 && Date.now() - prevEvent >= 6 * 36e5) fetch('/api/mira/proactive', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ state: loadState(), history: [], hoursAway: away, playerId: playerId() }) }).then(r => r.json()).then(data => { const e = data?.event; if (!e?.reply) return; setChat(c => [...c, { role: 'mira', text: e.reply, event: true }]); const p = [...loadJson<PhoneMessage[]>(PHONE_KEY, []), { id: uid(), direction: 'mira' as const, body: e.reply, kind: 'proactive', createdAt: Date.now() }]; persistPhone(p); void savePhone(p); const base = loadState(); persist({ ...base, trust: Math.max(-10, Math.min(10, base.trust + Number(e.trustDelta || 0))), closeness: Math.max(-10, Math.min(10, base.closeness + Number(e.closenessDelta || 0))), tension: Math.max(0, Math.min(10, base.tension + Number(e.tensionDelta || 0))), mood: moods.includes(e.mood) ? e.mood : base.mood, memories: typeof e.memory === 'string' && e.memory.trim() ? [...base.memories, { text: e.memory.trim(), createdAt: Date.now() }].slice(-30) : base.memories }); localStorage.setItem(LAST_EVENT_KEY, String(Date.now())); }).catch(() => {}); const { data: listener } = supabase.auth.onAuthStateChange((_e, session) => { if (session?.user) { setIdentity(session.user.email ? 'account' : 'device'); void saveRemote(loadState()); } }); return () => listener.subscription.unsubscribe(); }, []);
  const rel = useMemo(() => relationship(state), [state]); const moodLabel = { calm: 'спокойна', warm: 'теплеет', playful: 'играет', sad: 'грустит', curious: 'заинтересована', guarded: 'осторожна' }[state.mood]; const unread = phone.filter(m => m.direction === 'mira' && !m.readAt).length;
  async function send() { const text = input.trim(); if (!text || busy) return; setInput(''); setBusy(true); setChat(c => [...c, { role: 'user', text }]); const basePhone = loadJson<PhoneMessage[]>(PHONE_KEY, []), pm: PhoneMessage = { id: uid(), direction: 'player', body: text, kind: 'message', createdAt: Date.now() }, after = [...basePhone, pm]; persistPhone(after); void savePhone(after); try { const res = await fetch('/api/mira', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ message: text, state, history: chat.slice(-8), playerId: playerId() }) }); const data = await res.json(); const reply = data.reply || 'Я слушаю.'; setChat(c => [...c, { role: 'mira', text: reply }]); const afterReply = [...after, { id: uid(), direction: 'mira' as const, body: reply, kind: 'message', createdAt: Date.now() }]; persistPhone(afterReply); void savePhone(afterReply); const effects = data.effects || {}; persist({ ...state, trust: Math.max(-10, Math.min(10, state.trust + Number(effects.trustDelta || 0))), closeness: Math.max(-10, Math.min(10, state.closeness + Number(effects.closenessDelta || 0))), tension: Math.max(0, Math.min(10, state.tension + Number(effects.tensionDelta || 0))), mood: moods.includes(effects.mood) ? effects.mood : state.mood, memories: typeof data.memory === 'string' && data.memory.trim() ? [...state.memories, { text: data.memory.trim(), createdAt: Date.now() }].slice(-30) : state.memories }); void saveRemote(loadState()); } catch { setChat(c => [...c, { role: 'mira', text: 'Связь прервалась на секунду. Но разговор не потерян.' }]); } finally { setBusy(false); } }
  async function openPhone() { setPanel('phone'); const now = new Date().toISOString(); const next = phone.map(m => m.direction === 'mira' ? { ...m, readAt: m.readAt || now } : m); persistPhone(next); const { data: { session } } = await supabase.auth.getSession(); if (session?.user) await supabase.from('mira_phone_messages').update({ read_at: now }).eq('user_id', session.user.id).is('read_at', null); }
  async function createLife() { const res = await fetch('/api/mira/life', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ state, recentEvents: life.slice(-5) }) }); const data = await res.json(); if (!data?.event) return; const e = data.event; persistLife([...life, { id: uid(), title: e.title, body: e.body, kind: e.kind, mood: moods.includes(e.mood) ? e.mood : state.mood, occurredAt: Date.now() }]); setPanel('life'); }
  async function linkEmail() { const email = emailInput.trim(); if (!email.includes('@')) return; const { error } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: `${window.location.origin}/mira` } }); if (!error) { setEmailSent(true); setEmailInput(''); } }
  const miraPane = <aside className="mira-pane"><div className="mira-top"><div><span className="eyebrow">BETWEEN US / MIRA</span><h1>Мира</h1><p>Помнит тебя · {moodLabel}</p></div><div className="rel"><strong>{Math.round(rel)}</strong><span>связь</span></div></div><div className="relationship-line"><span style={{ width: `${rel}%` }} /></div><div className="mira-tabs"><button className={panel === 'chat' ? 'active' : ''} onClick={() => setPanel('chat')}>Разговор</button><button className={panel === 'phone' ? 'active' : ''} onClick={openPhone}>Телефон{unread > 0 && <b>{unread}</b>}</button><button className={panel === 'life' ? 'active' : ''} onClick={() => setPanel('life')}>Её жизнь</button></div>{panel === 'chat' && <><div className="chat">{chat.map((m, i) => <div key={i} className={`bubble ${m.role} ${m.event ? 'event' : ''}`}>{m.event && <small>Мира написала первой</small>}{m.text}</div>)}{busy && <div className="bubble mira typing">Мира печатает…</div>}</div><div className="composer"><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); void send(); } }} placeholder="Напиши Мире…" rows={1} /><button onClick={() => void send()} disabled={busy || !input.trim()}>Отправить</button></div></>}{panel === 'phone' && <div className="content-list">{phone.length ? [...phone].reverse().map(m => <article key={m.id} className={`phone-item ${m.direction}`}><small>{m.direction === 'mira' ? 'Мира' : 'Ты'} · {new Date(m.createdAt).toLocaleString('ru-RU', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })}</small><p>{m.body}</p></article>) : <div className="empty">Пока здесь тихо.</div>}</div>}{panel === 'life' && <div className="content-list"><button className="secondary" onClick={() => void createLife()}>Новый момент её жизни</button>{life.length ? [...life].reverse().map(e => <article className="life-card" key={e.id}><span>{e.kind === 'song' ? '♪' : e.kind === 'place' ? '⌖' : '·'}</span><div><small>{e.kind} · {new Date(e.occurredAt).toLocaleDateString('ru-RU')}</small><h3>{e.title}</h3><p>{e.body}</p></div></article>) : <div className="empty">У Миры ещё нет моментов.</div>}</div>}<div className="identity">{identity === 'account' ? <span>Память привязана к аккаунту</span> : <><span>{identity === 'device' ? 'Память сохранена на устройстве' : 'Локальная память'}</span><div><input value={emailInput} onChange={e => setEmailInput(e.target.value)} placeholder="email для переноса" /><button onClick={() => void linkEmail()}>Привязать</button>{emailSent && <em>Письмо отправлено</em>}</div></>}</div><footer>Мира — вымышленный цифровой персонаж. Её характер, память и отношения — часть игровой системы.</footer></aside>;
  return <main className="mira-shell"><div className="mobile-switch"><button className={mobileView === 'story' ? 'active' : ''} onClick={() => setMobileView('story')}>История</button><button className={mobileView === 'mira' ? 'active' : ''} onClick={() => setMobileView('mira')}>Мира{unread > 0 && <b>{unread}</b>}</button></div><section className="unified"><div className={`story-pane ${mobileView === 'mira' ? 'mobile-hidden' : ''}`}><div className="story-bar"><strong>BETWEEN US</strong><span>Квест · выбор меняет историю</span><button onClick={() => setStoryKey(k => k + 1)}>↻ Обновить</button></div><iframe key={storyKey} title="BETWEEN US — история" src="/?embedded=1" /></div><div className={`mira-wrap ${mobileView === 'story' ? 'mobile-hidden' : ''}`}>{miraPane}</div></section></main>;
}
